# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Tasks\Work\TimeDomainPlot\TimeDomainPlot.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.resize(945, 615)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(945, 614))
        MainWindow.setMaximumSize(QtCore.QSize(945, 615))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tabTimDomain = QtWidgets.QWidget()
        self.tabTimDomain.setObjectName("tabTimDomain")
        self.groupBox_TimeDomain = QtWidgets.QGroupBox(self.tabTimDomain)
        self.groupBox_TimeDomain.setGeometry(QtCore.QRect(0, 10, 111, 161))
        self.groupBox_TimeDomain.setObjectName("groupBox_TimeDomain")
        self.comboBox_TriggerDomain = QtWidgets.QComboBox(self.groupBox_TimeDomain)
        self.comboBox_TriggerDomain.setGeometry(QtCore.QRect(10, 40, 91, 22))
        self.comboBox_TriggerDomain.setObjectName("comboBox_TriggerDomain")
        self.comboBox_TriggerDomain.addItem("")
        self.comboBox_TriggerDomain.addItem("")
        self.label_Trigger_2 = QtWidgets.QLabel(self.groupBox_TimeDomain)
        self.label_Trigger_2.setGeometry(QtCore.QRect(10, 20, 47, 13))
        self.label_Trigger_2.setObjectName("label_Trigger_2")
        self.label_SampleNumber = QtWidgets.QLabel(self.groupBox_TimeDomain)
        self.label_SampleNumber.setGeometry(QtCore.QRect(10, 70, 81, 21))
        self.label_SampleNumber.setObjectName("label_SampleNumber")
        self.lineEdit_SampleRate = QtWidgets.QLineEdit(self.groupBox_TimeDomain)
        self.lineEdit_SampleRate.setGeometry(QtCore.QRect(10, 90, 51, 20))
        self.lineEdit_SampleRate.setToolTip("")
        self.lineEdit_SampleRate.setPlaceholderText("")
        self.lineEdit_SampleRate.setObjectName("lineEdit_SampleRate")
        self.label = QtWidgets.QLabel(self.groupBox_TimeDomain)
        self.label.setGeometry(QtCore.QRect(70, 90, 31, 16))
        self.label.setObjectName("label")
        self.lineEdit_RecordLength = QtWidgets.QLineEdit(self.groupBox_TimeDomain)
        self.lineEdit_RecordLength.setGeometry(QtCore.QRect(10, 130, 51, 20))
        self.lineEdit_RecordLength.setPlaceholderText("")
        self.lineEdit_RecordLength.setObjectName("lineEdit_RecordLength")
        self.label_SampleNumber_6 = QtWidgets.QLabel(self.groupBox_TimeDomain)
        self.label_SampleNumber_6.setGeometry(QtCore.QRect(10, 110, 81, 21))
        self.label_SampleNumber_6.setObjectName("label_SampleNumber_6")
        self.label_10 = QtWidgets.QLabel(self.groupBox_TimeDomain)
        self.label_10.setGeometry(QtCore.QRect(70, 130, 31, 16))
        self.label_10.setObjectName("label_10")
        self.widget_Signal_TimeDomain = QtWidgets.QWidget(self.tabTimDomain)
        self.widget_Signal_TimeDomain.setGeometry(QtCore.QRect(119, 10, 791, 561))
        self.widget_Signal_TimeDomain.setInputMethodHints(QtCore.Qt.ImhNone)
        self.widget_Signal_TimeDomain.setObjectName("widget_Signal_TimeDomain")
        self.pushButton_Stop_TimeDomain = QtWidgets.QPushButton(self.tabTimDomain)
        self.pushButton_Stop_TimeDomain.setEnabled(False)
        self.pushButton_Stop_TimeDomain.setGeometry(QtCore.QRect(10, 510, 82, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Stop_TimeDomain.sizePolicy().hasHeightForWidth())
        self.pushButton_Stop_TimeDomain.setSizePolicy(sizePolicy)
        self.pushButton_Stop_TimeDomain.setMinimumSize(QtCore.QSize(82, 23))
        self.pushButton_Stop_TimeDomain.setObjectName("pushButton_Stop_TimeDomain")
        self.pushButton_Start_TimeDomain = QtWidgets.QPushButton(self.tabTimDomain)
        self.pushButton_Start_TimeDomain.setEnabled(True)
        self.pushButton_Start_TimeDomain.setGeometry(QtCore.QRect(10, 480, 81, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Start_TimeDomain.sizePolicy().hasHeightForWidth())
        self.pushButton_Start_TimeDomain.setSizePolicy(sizePolicy)
        self.pushButton_Start_TimeDomain.setMinimumSize(QtCore.QSize(81, 23))
        self.pushButton_Start_TimeDomain.setObjectName("pushButton_Start_TimeDomain")
        self.groupBox_TimeDomain_2 = QtWidgets.QGroupBox(self.tabTimDomain)
        self.groupBox_TimeDomain_2.setGeometry(QtCore.QRect(0, 180, 111, 141))
        self.groupBox_TimeDomain_2.setObjectName("groupBox_TimeDomain_2")
        self.label_SampleNumber_2 = QtWidgets.QLabel(self.groupBox_TimeDomain_2)
        self.label_SampleNumber_2.setGeometry(QtCore.QRect(10, 20, 81, 21))
        self.label_SampleNumber_2.setObjectName("label_SampleNumber_2")
        self.lineEdit_VolScale = QtWidgets.QLineEdit(self.groupBox_TimeDomain_2)
        self.lineEdit_VolScale.setGeometry(QtCore.QRect(10, 50, 41, 20))
        self.lineEdit_VolScale.setToolTip("")
        self.lineEdit_VolScale.setPlaceholderText("")
        self.lineEdit_VolScale.setObjectName("lineEdit_VolScale")
        self.label_2 = QtWidgets.QLabel(self.groupBox_TimeDomain_2)
        self.label_2.setGeometry(QtCore.QRect(60, 50, 41, 20))
        self.label_2.setObjectName("label_2")
        self.lineEdit_Offset = QtWidgets.QLineEdit(self.groupBox_TimeDomain_2)
        self.lineEdit_Offset.setGeometry(QtCore.QRect(10, 110, 41, 20))
        self.lineEdit_Offset.setToolTip("")
        self.lineEdit_Offset.setPlaceholderText("")
        self.lineEdit_Offset.setObjectName("lineEdit_Offset")
        self.label_SampleNumber_3 = QtWidgets.QLabel(self.groupBox_TimeDomain_2)
        self.label_SampleNumber_3.setGeometry(QtCore.QRect(10, 80, 81, 21))
        self.label_SampleNumber_3.setObjectName("label_SampleNumber_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_TimeDomain_2)
        self.label_4.setGeometry(QtCore.QRect(60, 110, 41, 20))
        self.label_4.setObjectName("label_4")
        self.groupBox_TimeDomain_3 = QtWidgets.QGroupBox(self.tabTimDomain)
        self.groupBox_TimeDomain_3.setGeometry(QtCore.QRect(0, 330, 111, 91))
        self.groupBox_TimeDomain_3.setObjectName("groupBox_TimeDomain_3")
        self.label_SampleNumber_4 = QtWidgets.QLabel(self.groupBox_TimeDomain_3)
        self.label_SampleNumber_4.setEnabled(False)
        self.label_SampleNumber_4.setGeometry(QtCore.QRect(10, 40, 81, 21))
        self.label_SampleNumber_4.setObjectName("label_SampleNumber_4")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox_TimeDomain_3)
        self.lineEdit_4.setEnabled(False)
        self.lineEdit_4.setGeometry(QtCore.QRect(10, 60, 41, 20))
        self.lineEdit_4.setToolTip("")
        self.lineEdit_4.setPlaceholderText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_TimeDomain_3)
        self.checkBox.setGeometry(QtCore.QRect(10, 20, 70, 21))
        self.checkBox.setObjectName("checkBox")
        self.pushButton_Save_TimeDomain = QtWidgets.QPushButton(self.tabTimDomain)
        self.pushButton_Save_TimeDomain.setEnabled(False)
        self.pushButton_Save_TimeDomain.setGeometry(QtCore.QRect(10, 540, 82, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Save_TimeDomain.sizePolicy().hasHeightForWidth())
        self.pushButton_Save_TimeDomain.setSizePolicy(sizePolicy)
        self.pushButton_Save_TimeDomain.setMinimumSize(QtCore.QSize(82, 23))
        self.pushButton_Save_TimeDomain.setObjectName("pushButton_Save_TimeDomain")
        self.radioButton_CHA = QtWidgets.QRadioButton(self.tabTimDomain)
        self.radioButton_CHA.setGeometry(QtCore.QRect(10, 424, 82, 21))
        self.radioButton_CHA.setChecked(True)
        self.radioButton_CHA.setObjectName("radioButton_CHA")
        self.radioButton_CHB = QtWidgets.QRadioButton(self.tabTimDomain)
        self.radioButton_CHB.setGeometry(QtCore.QRect(10, 450, 82, 21))
        self.radioButton_CHB.setObjectName("radioButton_CHB")
        self.tabWidget.addTab(self.tabTimDomain, "")
        self.horizontalLayout_2.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.action3G = QtWidgets.QAction(MainWindow)
        self.action3G.setCheckable(True)
        self.action3G.setObjectName("action3G")
        self.action100M = QtWidgets.QAction(MainWindow)
        self.action100M.setCheckable(True)
        self.action100M.setObjectName("action100M")
        self.actionStart = QtWidgets.QAction(MainWindow)
        self.actionStart.setCheckable(True)
        self.actionStart.setObjectName("actionStart")
        self.actionStop = QtWidgets.QAction(MainWindow)
        self.actionStop.setCheckable(True)
        self.actionStop.setObjectName("actionStop")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Time-Domain Plot"))
        self.groupBox_TimeDomain.setTitle(_translate("MainWindow", "Horizontal Setting"))
        self.comboBox_TriggerDomain.setItemText(0, _translate("MainWindow", "Auto"))
        self.comboBox_TriggerDomain.setItemText(1, _translate("MainWindow", "External"))
        self.label_Trigger_2.setText(_translate("MainWindow", "Trigger:"))
        self.label_SampleNumber.setText(_translate("MainWindow", "Sample Rate:"))
        self.lineEdit_SampleRate.setText(_translate("MainWindow", "500"))
        self.label.setText(_translate("MainWindow", "MS/s"))
        self.lineEdit_RecordLength.setToolTip(_translate("MainWindow", "Please input 2* like 4/8/16... from 2 to 1024*1024"))
        self.lineEdit_RecordLength.setText(_translate("MainWindow", "4"))
        self.label_SampleNumber_6.setText(_translate("MainWindow", "Record Length:"))
        self.label_10.setText(_translate("MainWindow", "K"))
        self.pushButton_Stop_TimeDomain.setText(_translate("MainWindow", "Stop"))
        self.pushButton_Start_TimeDomain.setText(_translate("MainWindow", "Start"))
        self.groupBox_TimeDomain_2.setTitle(_translate("MainWindow", "Vertical Setting"))
        self.label_SampleNumber_2.setText(_translate("MainWindow", "Voltage Scale:"))
        self.lineEdit_VolScale.setText(_translate("MainWindow", "200"))
        self.label_2.setText(_translate("MainWindow", "mV/Div"))
        self.lineEdit_Offset.setText(_translate("MainWindow", "0"))
        self.label_SampleNumber_3.setText(_translate("MainWindow", "Offset:"))
        self.label_4.setText(_translate("MainWindow", "mV"))
        self.groupBox_TimeDomain_3.setTitle(_translate("MainWindow", "Frame Mode:"))
        self.label_SampleNumber_4.setText(_translate("MainWindow", " Number:"))
        self.lineEdit_4.setText(_translate("MainWindow", "10"))
        self.checkBox.setText(_translate("MainWindow", "Enable"))
        self.pushButton_Save_TimeDomain.setText(_translate("MainWindow", "Save"))
        self.radioButton_CHA.setText(_translate("MainWindow", "Channel A"))
        self.radioButton_CHB.setText(_translate("MainWindow", "Channel B"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTimDomain), _translate("MainWindow", "Time-Domain Plot"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.action3G.setText(_translate("MainWindow", "3G"))
        self.action100M.setText(_translate("MainWindow", "100M"))
        self.actionStart.setText(_translate("MainWindow", "Start"))
        self.actionStop.setText(_translate("MainWindow", "Stop"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

