# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Tasks\Work\TimeDomainPlot\TimeDomainPlot.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.resize(945, 615)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(945, 614))
        MainWindow.setMaximumSize(QtCore.QSize(945, 615))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tabRealTime = QtWidgets.QWidget()
        self.tabRealTime.setObjectName("tabRealTime")
        self.widget_Signal_RealTime = QtWidgets.QWidget(self.tabRealTime)
        self.widget_Signal_RealTime.setGeometry(QtCore.QRect(119, 0, 801, 521))
        self.widget_Signal_RealTime.setInputMethodHints(QtCore.Qt.ImhNone)
        self.widget_Signal_RealTime.setObjectName("widget_Signal_RealTime")
        self.radioButton_CHA_RealTime = QtWidgets.QRadioButton(self.tabRealTime)
        self.radioButton_CHA_RealTime.setGeometry(QtCore.QRect(10, 30, 91, 17))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_CHA_RealTime.sizePolicy().hasHeightForWidth())
        self.radioButton_CHA_RealTime.setSizePolicy(sizePolicy)
        self.radioButton_CHA_RealTime.setMinimumSize(QtCore.QSize(72, 17))
        self.radioButton_CHA_RealTime.setChecked(True)
        self.radioButton_CHA_RealTime.setObjectName("radioButton_CHA_RealTime")
        self.radioButton_CHB_RealTime = QtWidgets.QRadioButton(self.tabRealTime)
        self.radioButton_CHB_RealTime.setGeometry(QtCore.QRect(10, 50, 91, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_CHB_RealTime.sizePolicy().hasHeightForWidth())
        self.radioButton_CHB_RealTime.setSizePolicy(sizePolicy)
        self.radioButton_CHB_RealTime.setMinimumSize(QtCore.QSize(82, 23))
        self.radioButton_CHB_RealTime.setChecked(False)
        self.radioButton_CHB_RealTime.setObjectName("radioButton_CHB_RealTime")
        self.checkBox_ShowGrid_RealTime = QtWidgets.QCheckBox(self.tabRealTime)
        self.checkBox_ShowGrid_RealTime.setGeometry(QtCore.QRect(10, 80, 91, 17))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_ShowGrid_RealTime.sizePolicy().hasHeightForWidth())
        self.checkBox_ShowGrid_RealTime.setSizePolicy(sizePolicy)
        self.checkBox_ShowGrid_RealTime.setMinimumSize(QtCore.QSize(71, 17))
        self.checkBox_ShowGrid_RealTime.setChecked(True)
        self.checkBox_ShowGrid_RealTime.setObjectName("checkBox_ShowGrid_RealTime")
        self.pushButton_Start_RealTime = QtWidgets.QPushButton(self.tabRealTime)
        self.pushButton_Start_RealTime.setEnabled(True)
        self.pushButton_Start_RealTime.setGeometry(QtCore.QRect(20, 430, 81, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Start_RealTime.sizePolicy().hasHeightForWidth())
        self.pushButton_Start_RealTime.setSizePolicy(sizePolicy)
        self.pushButton_Start_RealTime.setMinimumSize(QtCore.QSize(81, 23))
        self.pushButton_Start_RealTime.setObjectName("pushButton_Start_RealTime")
        self.pushButton_Stop_RealTime = QtWidgets.QPushButton(self.tabRealTime)
        self.pushButton_Stop_RealTime.setEnabled(True)
        self.pushButton_Stop_RealTime.setGeometry(QtCore.QRect(20, 460, 82, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Stop_RealTime.sizePolicy().hasHeightForWidth())
        self.pushButton_Stop_RealTime.setSizePolicy(sizePolicy)
        self.pushButton_Stop_RealTime.setMinimumSize(QtCore.QSize(82, 23))
        self.pushButton_Stop_RealTime.setObjectName("pushButton_Stop_RealTime")
        self.groupBox_Scale = QtWidgets.QGroupBox(self.tabRealTime)
        self.groupBox_Scale.setGeometry(QtCore.QRect(10, 170, 91, 51))
        self.groupBox_Scale.setObjectName("groupBox_Scale")
        self.lineEdit_Scale = QtWidgets.QLineEdit(self.groupBox_Scale)
        self.lineEdit_Scale.setGeometry(QtCore.QRect(10, 20, 41, 20))
        self.lineEdit_Scale.setObjectName("lineEdit_Scale")
        self.label_3 = QtWidgets.QLabel(self.groupBox_Scale)
        self.label_3.setGeometry(QtCore.QRect(60, 20, 21, 16))
        self.label_3.setObjectName("label_3")
        self.groupBox_Ref = QtWidgets.QGroupBox(self.tabRealTime)
        self.groupBox_Ref.setGeometry(QtCore.QRect(10, 110, 91, 51))
        self.groupBox_Ref.setObjectName("groupBox_Ref")
        self.lineEdit_RefLevel = QtWidgets.QLineEdit(self.groupBox_Ref)
        self.lineEdit_RefLevel.setGeometry(QtCore.QRect(10, 20, 41, 20))
        self.lineEdit_RefLevel.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.lineEdit_RefLevel.setObjectName("lineEdit_RefLevel")
        self.label_7 = QtWidgets.QLabel(self.groupBox_Ref)
        self.label_7.setGeometry(QtCore.QRect(60, 20, 21, 16))
        self.label_7.setObjectName("label_7")
        self.groupBox_StartFreq = QtWidgets.QGroupBox(self.tabRealTime)
        self.groupBox_StartFreq.setGeometry(QtCore.QRect(10, 240, 91, 51))
        self.groupBox_StartFreq.setObjectName("groupBox_StartFreq")
        self.lineEdit_StartFreq = QtWidgets.QLineEdit(self.groupBox_StartFreq)
        self.lineEdit_StartFreq.setGeometry(QtCore.QRect(10, 20, 41, 20))
        self.lineEdit_StartFreq.setObjectName("lineEdit_StartFreq")
        self.label_8 = QtWidgets.QLabel(self.groupBox_StartFreq)
        self.label_8.setGeometry(QtCore.QRect(60, 20, 21, 16))
        self.label_8.setObjectName("label_8")
        self.groupBox_StopFreq = QtWidgets.QGroupBox(self.tabRealTime)
        self.groupBox_StopFreq.setGeometry(QtCore.QRect(10, 310, 91, 51))
        self.groupBox_StopFreq.setObjectName("groupBox_StopFreq")
        self.lineEdit_StopFreq = QtWidgets.QLineEdit(self.groupBox_StopFreq)
        self.lineEdit_StopFreq.setGeometry(QtCore.QRect(10, 20, 41, 20))
        self.lineEdit_StopFreq.setObjectName("lineEdit_StopFreq")
        self.label_9 = QtWidgets.QLabel(self.groupBox_StopFreq)
        self.label_9.setGeometry(QtCore.QRect(60, 20, 21, 16))
        self.label_9.setObjectName("label_9")
        self.groupBox_RealTimeSetting = QtWidgets.QGroupBox(self.tabRealTime)
        self.groupBox_RealTimeSetting.setGeometry(QtCore.QRect(0, 10, 111, 371))
        self.groupBox_RealTimeSetting.setObjectName("groupBox_RealTimeSetting")
        self.groupBox_RealTimeSetting.raise_()
        self.widget_Signal_RealTime.raise_()
        self.radioButton_CHA_RealTime.raise_()
        self.radioButton_CHB_RealTime.raise_()
        self.checkBox_ShowGrid_RealTime.raise_()
        self.pushButton_Start_RealTime.raise_()
        self.pushButton_Stop_RealTime.raise_()
        self.groupBox_Scale.raise_()
        self.groupBox_Ref.raise_()
        self.groupBox_StartFreq.raise_()
        self.groupBox_StopFreq.raise_()
        self.tabWidget.addTab(self.tabRealTime, "")
        self.tabTimDomain = QtWidgets.QWidget()
        self.tabTimDomain.setObjectName("tabTimDomain")
        self.groupBox_TimeDomain = QtWidgets.QGroupBox(self.tabTimDomain)
        self.groupBox_TimeDomain.setGeometry(QtCore.QRect(0, 10, 111, 161))
        self.groupBox_TimeDomain.setObjectName("groupBox_TimeDomain")
        self.comboBox_TriggerDomain = QtWidgets.QComboBox(self.groupBox_TimeDomain)
        self.comboBox_TriggerDomain.setGeometry(QtCore.QRect(10, 40, 91, 22))
        self.comboBox_TriggerDomain.setObjectName("comboBox_TriggerDomain")
        self.comboBox_TriggerDomain.addItem("")
        self.comboBox_TriggerDomain.addItem("")
        self.label_Trigger_2 = QtWidgets.QLabel(self.groupBox_TimeDomain)
        self.label_Trigger_2.setGeometry(QtCore.QRect(10, 20, 47, 13))
        self.label_Trigger_2.setObjectName("label_Trigger_2")
        self.label_SampleNumber = QtWidgets.QLabel(self.groupBox_TimeDomain)
        self.label_SampleNumber.setGeometry(QtCore.QRect(10, 60, 81, 21))
        self.label_SampleNumber.setObjectName("label_SampleNumber")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_TimeDomain)
        self.lineEdit.setGeometry(QtCore.QRect(10, 80, 51, 20))
        self.lineEdit.setPlaceholderText("")
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self.groupBox_TimeDomain)
        self.label.setGeometry(QtCore.QRect(70, 80, 31, 16))
        self.label.setObjectName("label")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox_TimeDomain)
        self.lineEdit_6.setGeometry(QtCore.QRect(10, 120, 51, 20))
        self.lineEdit_6.setPlaceholderText("")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_SampleNumber_6 = QtWidgets.QLabel(self.groupBox_TimeDomain)
        self.label_SampleNumber_6.setGeometry(QtCore.QRect(10, 100, 81, 21))
        self.label_SampleNumber_6.setObjectName("label_SampleNumber_6")
        self.label_10 = QtWidgets.QLabel(self.groupBox_TimeDomain)
        self.label_10.setGeometry(QtCore.QRect(70, 120, 31, 16))
        self.label_10.setObjectName("label_10")
        self.widget_Signal_TimeDomain = QtWidgets.QWidget(self.tabTimDomain)
        self.widget_Signal_TimeDomain.setGeometry(QtCore.QRect(119, -10, 811, 521))
        self.widget_Signal_TimeDomain.setInputMethodHints(QtCore.Qt.ImhNone)
        self.widget_Signal_TimeDomain.setObjectName("widget_Signal_TimeDomain")
        self.pushButton_Stop_TimeDomain = QtWidgets.QPushButton(self.tabTimDomain)
        self.pushButton_Stop_TimeDomain.setEnabled(True)
        self.pushButton_Stop_TimeDomain.setGeometry(QtCore.QRect(10, 470, 82, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Stop_TimeDomain.sizePolicy().hasHeightForWidth())
        self.pushButton_Stop_TimeDomain.setSizePolicy(sizePolicy)
        self.pushButton_Stop_TimeDomain.setMinimumSize(QtCore.QSize(82, 23))
        self.pushButton_Stop_TimeDomain.setObjectName("pushButton_Stop_TimeDomain")
        self.pushButton_Start_TimeDomain = QtWidgets.QPushButton(self.tabTimDomain)
        self.pushButton_Start_TimeDomain.setEnabled(True)
        self.pushButton_Start_TimeDomain.setGeometry(QtCore.QRect(10, 440, 81, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Start_TimeDomain.sizePolicy().hasHeightForWidth())
        self.pushButton_Start_TimeDomain.setSizePolicy(sizePolicy)
        self.pushButton_Start_TimeDomain.setMinimumSize(QtCore.QSize(81, 23))
        self.pushButton_Start_TimeDomain.setObjectName("pushButton_Start_TimeDomain")
        self.groupBox_TimeDomain_2 = QtWidgets.QGroupBox(self.tabTimDomain)
        self.groupBox_TimeDomain_2.setGeometry(QtCore.QRect(0, 180, 111, 151))
        self.groupBox_TimeDomain_2.setObjectName("groupBox_TimeDomain_2")
        self.label_SampleNumber_2 = QtWidgets.QLabel(self.groupBox_TimeDomain_2)
        self.label_SampleNumber_2.setGeometry(QtCore.QRect(10, 20, 81, 21))
        self.label_SampleNumber_2.setObjectName("label_SampleNumber_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_TimeDomain_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 50, 41, 20))
        self.lineEdit_2.setToolTip("")
        self.lineEdit_2.setPlaceholderText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_TimeDomain_2)
        self.label_2.setGeometry(QtCore.QRect(60, 50, 41, 20))
        self.label_2.setObjectName("label_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_TimeDomain_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(10, 110, 41, 20))
        self.lineEdit_3.setToolTip("")
        self.lineEdit_3.setPlaceholderText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_SampleNumber_3 = QtWidgets.QLabel(self.groupBox_TimeDomain_2)
        self.label_SampleNumber_3.setGeometry(QtCore.QRect(10, 80, 81, 21))
        self.label_SampleNumber_3.setObjectName("label_SampleNumber_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_TimeDomain_2)
        self.label_4.setGeometry(QtCore.QRect(60, 110, 41, 20))
        self.label_4.setObjectName("label_4")
        self.groupBox_TimeDomain_3 = QtWidgets.QGroupBox(self.tabTimDomain)
        self.groupBox_TimeDomain_3.setGeometry(QtCore.QRect(0, 340, 111, 91))
        self.groupBox_TimeDomain_3.setObjectName("groupBox_TimeDomain_3")
        self.label_SampleNumber_4 = QtWidgets.QLabel(self.groupBox_TimeDomain_3)
        self.label_SampleNumber_4.setEnabled(False)
        self.label_SampleNumber_4.setGeometry(QtCore.QRect(10, 40, 81, 21))
        self.label_SampleNumber_4.setObjectName("label_SampleNumber_4")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox_TimeDomain_3)
        self.lineEdit_4.setEnabled(False)
        self.lineEdit_4.setGeometry(QtCore.QRect(10, 60, 41, 20))
        self.lineEdit_4.setToolTip("")
        self.lineEdit_4.setPlaceholderText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_TimeDomain_3)
        self.checkBox.setGeometry(QtCore.QRect(10, 20, 70, 21))
        self.checkBox.setObjectName("checkBox")
        self.pushButton_Save_TimeDomain = QtWidgets.QPushButton(self.tabTimDomain)
        self.pushButton_Save_TimeDomain.setEnabled(True)
        self.pushButton_Save_TimeDomain.setGeometry(QtCore.QRect(10, 500, 82, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Save_TimeDomain.sizePolicy().hasHeightForWidth())
        self.pushButton_Save_TimeDomain.setSizePolicy(sizePolicy)
        self.pushButton_Save_TimeDomain.setMinimumSize(QtCore.QSize(82, 23))
        self.pushButton_Save_TimeDomain.setObjectName("pushButton_Save_TimeDomain")
        self.tabWidget.addTab(self.tabTimDomain, "")
        self.horizontalLayout_2.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.action3G = QtWidgets.QAction(MainWindow)
        self.action3G.setCheckable(True)
        self.action3G.setObjectName("action3G")
        self.action100M = QtWidgets.QAction(MainWindow)
        self.action100M.setCheckable(True)
        self.action100M.setObjectName("action100M")
        self.actionStart = QtWidgets.QAction(MainWindow)
        self.actionStart.setCheckable(True)
        self.actionStart.setObjectName("actionStart")
        self.actionStop = QtWidgets.QAction(MainWindow)
        self.actionStop.setCheckable(True)
        self.actionStop.setObjectName("actionStop")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Time-Domain Plot"))
        self.radioButton_CHA_RealTime.setText(_translate("MainWindow", "Channel A"))
        self.radioButton_CHB_RealTime.setText(_translate("MainWindow", "Channel B"))
        self.checkBox_ShowGrid_RealTime.setText(_translate("MainWindow", "Show Grid"))
        self.pushButton_Start_RealTime.setText(_translate("MainWindow", "Start"))
        self.pushButton_Stop_RealTime.setText(_translate("MainWindow", "Stop"))
        self.groupBox_Scale.setTitle(_translate("MainWindow", "Scale/div:"))
        self.lineEdit_Scale.setText(_translate("MainWindow", "10"))
        self.label_3.setText(_translate("MainWindow", "dBm"))
        self.groupBox_Ref.setTitle(_translate("MainWindow", "Ref Level:"))
        self.lineEdit_RefLevel.setText(_translate("MainWindow", "0"))
        self.label_7.setText(_translate("MainWindow", "dBm"))
        self.groupBox_StartFreq.setTitle(_translate("MainWindow", "Start Freq:"))
        self.lineEdit_StartFreq.setText(_translate("MainWindow", "100"))
        self.label_8.setText(_translate("MainWindow", "MHz"))
        self.groupBox_StopFreq.setTitle(_translate("MainWindow", "Stop Freq:"))
        self.lineEdit_StopFreq.setText(_translate("MainWindow", "1400"))
        self.label_9.setText(_translate("MainWindow", "MHz"))
        self.groupBox_RealTimeSetting.setTitle(_translate("MainWindow", "Settings"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabRealTime), _translate("MainWindow", "Real Time Capture"))
        self.groupBox_TimeDomain.setTitle(_translate("MainWindow", "Horizontal Setting"))
        self.comboBox_TriggerDomain.setItemText(0, _translate("MainWindow", "Auto"))
        self.comboBox_TriggerDomain.setItemText(1, _translate("MainWindow", "External"))
        self.label_Trigger_2.setText(_translate("MainWindow", "Trigger:"))
        self.label_SampleNumber.setText(_translate("MainWindow", "Sample Rate:"))
        self.lineEdit.setToolTip(_translate("MainWindow", "Please input 2* like 1/2/4/8... from 1 to 1024*1024"))
        self.lineEdit.setText(_translate("MainWindow", "500"))
        self.label.setText(_translate("MainWindow", "MS/s"))
        self.lineEdit_6.setToolTip(_translate("MainWindow", "Please input 2* like 1/2/4/8... from 1 to 1024*1024"))
        self.lineEdit_6.setText(_translate("MainWindow", "1"))
        self.label_SampleNumber_6.setText(_translate("MainWindow", "Record Length:"))
        self.label_10.setText(_translate("MainWindow", "K"))
        self.pushButton_Stop_TimeDomain.setText(_translate("MainWindow", "Stop"))
        self.pushButton_Start_TimeDomain.setText(_translate("MainWindow", "Start"))
        self.groupBox_TimeDomain_2.setTitle(_translate("MainWindow", "Vertical Setting"))
        self.label_SampleNumber_2.setText(_translate("MainWindow", "Voltage Scale:"))
        self.lineEdit_2.setText(_translate("MainWindow", "200"))
        self.label_2.setText(_translate("MainWindow", "mV/Div"))
        self.lineEdit_3.setText(_translate("MainWindow", "0"))
        self.label_SampleNumber_3.setText(_translate("MainWindow", "Offset:"))
        self.label_4.setText(_translate("MainWindow", "mV"))
        self.groupBox_TimeDomain_3.setTitle(_translate("MainWindow", "Frame Mode:"))
        self.label_SampleNumber_4.setText(_translate("MainWindow", " Number:"))
        self.lineEdit_4.setText(_translate("MainWindow", "10"))
        self.checkBox.setText(_translate("MainWindow", "Enable"))
        self.pushButton_Save_TimeDomain.setText(_translate("MainWindow", "Save"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTimDomain), _translate("MainWindow", "Time-Domain Plot"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.action3G.setText(_translate("MainWindow", "3G"))
        self.action100M.setText(_translate("MainWindow", "100M"))
        self.actionStart.setText(_translate("MainWindow", "Start"))
        self.actionStop.setText(_translate("MainWindow", "Stop"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

